; PioArduino / PlatformIO project configuration
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; PioArduino IDE uses the same platformio.ini project format.
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_esp32_p4_nano]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = waveshare_esp32_p4_nano
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.partitions = huge_app_16mb.csv

build_flags =
  -DBOARD_HAS_PSRAM
  -IS:/.secrets

lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson
